// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mymessages.proto

package info.chenliang.myserver.messages;

public final class MyMessages {
  private MyMessages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registry.add(info.chenliang.myserver.messages.MyMessages.VersionRequest.id);
    registry.add(info.chenliang.myserver.messages.MyMessages.VersionResponse.id);
  }
  public interface MessageBaseOrBuilder extends
      com.google.protobuf.GeneratedMessage.
          ExtendableMessageOrBuilder<MessageBase> {

    // required .info.chenliang.myserver.messages.MessageBase.MessageType type = 1;
    /**
     * <code>required .info.chenliang.myserver.messages.MessageBase.MessageType type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>required .info.chenliang.myserver.messages.MessageBase.MessageType type = 1;</code>
     */
    info.chenliang.myserver.messages.MyMessages.MessageBase.MessageType getType();
  }
  /**
   * Protobuf type {@code info.chenliang.myserver.messages.MessageBase}
   */
  public static final class MessageBase extends
      com.google.protobuf.GeneratedMessage.ExtendableMessage<
        MessageBase> implements MessageBaseOrBuilder {
    // Use MessageBase.newBuilder() to construct.
    private MessageBase(com.google.protobuf.GeneratedMessage.ExtendableBuilder<info.chenliang.myserver.messages.MyMessages.MessageBase, ?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MessageBase(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MessageBase defaultInstance;
    public static MessageBase getDefaultInstance() {
      return defaultInstance;
    }

    public MessageBase getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MessageBase(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              info.chenliang.myserver.messages.MyMessages.MessageBase.MessageType value = info.chenliang.myserver.messages.MyMessages.MessageBase.MessageType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return info.chenliang.myserver.messages.MyMessages.internal_static_info_chenliang_myserver_messages_MessageBase_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return info.chenliang.myserver.messages.MyMessages.internal_static_info_chenliang_myserver_messages_MessageBase_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              info.chenliang.myserver.messages.MyMessages.MessageBase.class, info.chenliang.myserver.messages.MyMessages.MessageBase.Builder.class);
    }

    public static com.google.protobuf.Parser<MessageBase> PARSER =
        new com.google.protobuf.AbstractParser<MessageBase>() {
      public MessageBase parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MessageBase(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MessageBase> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code info.chenliang.myserver.messages.MessageBase.MessageType}
     */
    public enum MessageType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>VERSION_REQUEST = 1;</code>
       */
      VERSION_REQUEST(0, 1),
      /**
       * <code>VERSION_RESPONSE = 2;</code>
       */
      VERSION_RESPONSE(1, 2),
      ;

      /**
       * <code>VERSION_REQUEST = 1;</code>
       */
      public static final int VERSION_REQUEST_VALUE = 1;
      /**
       * <code>VERSION_RESPONSE = 2;</code>
       */
      public static final int VERSION_RESPONSE_VALUE = 2;


      public final int getNumber() { return value; }

      public static MessageType valueOf(int value) {
        switch (value) {
          case 1: return VERSION_REQUEST;
          case 2: return VERSION_RESPONSE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<MessageType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
              public MessageType findValueByNumber(int number) {
                return MessageType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return info.chenliang.myserver.messages.MyMessages.MessageBase.getDescriptor().getEnumTypes().get(0);
      }

      private static final MessageType[] VALUES = values();

      public static MessageType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private MessageType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:info.chenliang.myserver.messages.MessageBase.MessageType)
    }

    private int bitField0_;
    // required .info.chenliang.myserver.messages.MessageBase.MessageType type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private info.chenliang.myserver.messages.MyMessages.MessageBase.MessageType type_;
    /**
     * <code>required .info.chenliang.myserver.messages.MessageBase.MessageType type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .info.chenliang.myserver.messages.MessageBase.MessageType type = 1;</code>
     */
    public info.chenliang.myserver.messages.MyMessages.MessageBase.MessageType getType() {
      return type_;
    }

    private void initFields() {
      type_ = info.chenliang.myserver.messages.MyMessages.MessageBase.MessageType.VERSION_REQUEST;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!extensionsAreInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      com.google.protobuf.GeneratedMessage
        .ExtendableMessage<info.chenliang.myserver.messages.MyMessages.MessageBase>.ExtensionWriter extensionWriter =
          newExtensionWriter();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      extensionWriter.writeUntil(536870912, output);
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      size += extensionsSerializedSize();
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static info.chenliang.myserver.messages.MyMessages.MessageBase parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static info.chenliang.myserver.messages.MyMessages.MessageBase parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static info.chenliang.myserver.messages.MyMessages.MessageBase parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static info.chenliang.myserver.messages.MyMessages.MessageBase parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static info.chenliang.myserver.messages.MyMessages.MessageBase parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static info.chenliang.myserver.messages.MyMessages.MessageBase parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static info.chenliang.myserver.messages.MyMessages.MessageBase parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static info.chenliang.myserver.messages.MyMessages.MessageBase parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static info.chenliang.myserver.messages.MyMessages.MessageBase parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static info.chenliang.myserver.messages.MyMessages.MessageBase parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(info.chenliang.myserver.messages.MyMessages.MessageBase prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code info.chenliang.myserver.messages.MessageBase}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.ExtendableBuilder<
          info.chenliang.myserver.messages.MyMessages.MessageBase, Builder> implements info.chenliang.myserver.messages.MyMessages.MessageBaseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return info.chenliang.myserver.messages.MyMessages.internal_static_info_chenliang_myserver_messages_MessageBase_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return info.chenliang.myserver.messages.MyMessages.internal_static_info_chenliang_myserver_messages_MessageBase_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                info.chenliang.myserver.messages.MyMessages.MessageBase.class, info.chenliang.myserver.messages.MyMessages.MessageBase.Builder.class);
      }

      // Construct using info.chenliang.myserver.messages.MyMessages.MessageBase.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = info.chenliang.myserver.messages.MyMessages.MessageBase.MessageType.VERSION_REQUEST;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return info.chenliang.myserver.messages.MyMessages.internal_static_info_chenliang_myserver_messages_MessageBase_descriptor;
      }

      public info.chenliang.myserver.messages.MyMessages.MessageBase getDefaultInstanceForType() {
        return info.chenliang.myserver.messages.MyMessages.MessageBase.getDefaultInstance();
      }

      public info.chenliang.myserver.messages.MyMessages.MessageBase build() {
        info.chenliang.myserver.messages.MyMessages.MessageBase result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public info.chenliang.myserver.messages.MyMessages.MessageBase buildPartial() {
        info.chenliang.myserver.messages.MyMessages.MessageBase result = new info.chenliang.myserver.messages.MyMessages.MessageBase(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof info.chenliang.myserver.messages.MyMessages.MessageBase) {
          return mergeFrom((info.chenliang.myserver.messages.MyMessages.MessageBase)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(info.chenliang.myserver.messages.MyMessages.MessageBase other) {
        if (other == info.chenliang.myserver.messages.MyMessages.MessageBase.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        this.mergeExtensionFields(other);
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        if (!extensionsAreInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        info.chenliang.myserver.messages.MyMessages.MessageBase parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (info.chenliang.myserver.messages.MyMessages.MessageBase) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .info.chenliang.myserver.messages.MessageBase.MessageType type = 1;
      private info.chenliang.myserver.messages.MyMessages.MessageBase.MessageType type_ = info.chenliang.myserver.messages.MyMessages.MessageBase.MessageType.VERSION_REQUEST;
      /**
       * <code>required .info.chenliang.myserver.messages.MessageBase.MessageType type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .info.chenliang.myserver.messages.MessageBase.MessageType type = 1;</code>
       */
      public info.chenliang.myserver.messages.MyMessages.MessageBase.MessageType getType() {
        return type_;
      }
      /**
       * <code>required .info.chenliang.myserver.messages.MessageBase.MessageType type = 1;</code>
       */
      public Builder setType(info.chenliang.myserver.messages.MyMessages.MessageBase.MessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .info.chenliang.myserver.messages.MessageBase.MessageType type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = info.chenliang.myserver.messages.MyMessages.MessageBase.MessageType.VERSION_REQUEST;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:info.chenliang.myserver.messages.MessageBase)
    }

    static {
      defaultInstance = new MessageBase(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:info.chenliang.myserver.messages.MessageBase)
  }

  public interface VersionRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code info.chenliang.myserver.messages.VersionRequest}
   */
  public static final class VersionRequest extends
      com.google.protobuf.GeneratedMessage
      implements VersionRequestOrBuilder {
    // Use VersionRequest.newBuilder() to construct.
    private VersionRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private VersionRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final VersionRequest defaultInstance;
    public static VersionRequest getDefaultInstance() {
      return defaultInstance;
    }

    public VersionRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private VersionRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return info.chenliang.myserver.messages.MyMessages.internal_static_info_chenliang_myserver_messages_VersionRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return info.chenliang.myserver.messages.MyMessages.internal_static_info_chenliang_myserver_messages_VersionRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              info.chenliang.myserver.messages.MyMessages.VersionRequest.class, info.chenliang.myserver.messages.MyMessages.VersionRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<VersionRequest> PARSER =
        new com.google.protobuf.AbstractParser<VersionRequest>() {
      public VersionRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new VersionRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<VersionRequest> getParserForType() {
      return PARSER;
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static info.chenliang.myserver.messages.MyMessages.VersionRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static info.chenliang.myserver.messages.MyMessages.VersionRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static info.chenliang.myserver.messages.MyMessages.VersionRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static info.chenliang.myserver.messages.MyMessages.VersionRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static info.chenliang.myserver.messages.MyMessages.VersionRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static info.chenliang.myserver.messages.MyMessages.VersionRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static info.chenliang.myserver.messages.MyMessages.VersionRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static info.chenliang.myserver.messages.MyMessages.VersionRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static info.chenliang.myserver.messages.MyMessages.VersionRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static info.chenliang.myserver.messages.MyMessages.VersionRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(info.chenliang.myserver.messages.MyMessages.VersionRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code info.chenliang.myserver.messages.VersionRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements info.chenliang.myserver.messages.MyMessages.VersionRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return info.chenliang.myserver.messages.MyMessages.internal_static_info_chenliang_myserver_messages_VersionRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return info.chenliang.myserver.messages.MyMessages.internal_static_info_chenliang_myserver_messages_VersionRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                info.chenliang.myserver.messages.MyMessages.VersionRequest.class, info.chenliang.myserver.messages.MyMessages.VersionRequest.Builder.class);
      }

      // Construct using info.chenliang.myserver.messages.MyMessages.VersionRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return info.chenliang.myserver.messages.MyMessages.internal_static_info_chenliang_myserver_messages_VersionRequest_descriptor;
      }

      public info.chenliang.myserver.messages.MyMessages.VersionRequest getDefaultInstanceForType() {
        return info.chenliang.myserver.messages.MyMessages.VersionRequest.getDefaultInstance();
      }

      public info.chenliang.myserver.messages.MyMessages.VersionRequest build() {
        info.chenliang.myserver.messages.MyMessages.VersionRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public info.chenliang.myserver.messages.MyMessages.VersionRequest buildPartial() {
        info.chenliang.myserver.messages.MyMessages.VersionRequest result = new info.chenliang.myserver.messages.MyMessages.VersionRequest(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof info.chenliang.myserver.messages.MyMessages.VersionRequest) {
          return mergeFrom((info.chenliang.myserver.messages.MyMessages.VersionRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(info.chenliang.myserver.messages.MyMessages.VersionRequest other) {
        if (other == info.chenliang.myserver.messages.MyMessages.VersionRequest.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        info.chenliang.myserver.messages.MyMessages.VersionRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (info.chenliang.myserver.messages.MyMessages.VersionRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:info.chenliang.myserver.messages.VersionRequest)
    }

    static {
      defaultInstance = new VersionRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:info.chenliang.myserver.messages.VersionRequest)
    public static final int ID_FIELD_NUMBER = 10000;
    /**
     * <code>extend .info.chenliang.myserver.messages.MessageBase { ... }</code>
     */
    public static final
      com.google.protobuf.GeneratedMessage.GeneratedExtension<
        info.chenliang.myserver.messages.MyMessages.MessageBase,
        info.chenliang.myserver.messages.MyMessages.VersionRequest> id = com.google.protobuf.GeneratedMessage
            .newMessageScopedGeneratedExtension(
          info.chenliang.myserver.messages.MyMessages.VersionRequest.getDefaultInstance(),
          0,
          info.chenliang.myserver.messages.MyMessages.VersionRequest.class,
          info.chenliang.myserver.messages.MyMessages.VersionRequest.getDefaultInstance());
  }

  public interface VersionResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code info.chenliang.myserver.messages.VersionResponse}
   */
  public static final class VersionResponse extends
      com.google.protobuf.GeneratedMessage
      implements VersionResponseOrBuilder {
    // Use VersionResponse.newBuilder() to construct.
    private VersionResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private VersionResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final VersionResponse defaultInstance;
    public static VersionResponse getDefaultInstance() {
      return defaultInstance;
    }

    public VersionResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private VersionResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return info.chenliang.myserver.messages.MyMessages.internal_static_info_chenliang_myserver_messages_VersionResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return info.chenliang.myserver.messages.MyMessages.internal_static_info_chenliang_myserver_messages_VersionResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              info.chenliang.myserver.messages.MyMessages.VersionResponse.class, info.chenliang.myserver.messages.MyMessages.VersionResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<VersionResponse> PARSER =
        new com.google.protobuf.AbstractParser<VersionResponse>() {
      public VersionResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new VersionResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<VersionResponse> getParserForType() {
      return PARSER;
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static info.chenliang.myserver.messages.MyMessages.VersionResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static info.chenliang.myserver.messages.MyMessages.VersionResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static info.chenliang.myserver.messages.MyMessages.VersionResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static info.chenliang.myserver.messages.MyMessages.VersionResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static info.chenliang.myserver.messages.MyMessages.VersionResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static info.chenliang.myserver.messages.MyMessages.VersionResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static info.chenliang.myserver.messages.MyMessages.VersionResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static info.chenliang.myserver.messages.MyMessages.VersionResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static info.chenliang.myserver.messages.MyMessages.VersionResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static info.chenliang.myserver.messages.MyMessages.VersionResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(info.chenliang.myserver.messages.MyMessages.VersionResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code info.chenliang.myserver.messages.VersionResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements info.chenliang.myserver.messages.MyMessages.VersionResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return info.chenliang.myserver.messages.MyMessages.internal_static_info_chenliang_myserver_messages_VersionResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return info.chenliang.myserver.messages.MyMessages.internal_static_info_chenliang_myserver_messages_VersionResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                info.chenliang.myserver.messages.MyMessages.VersionResponse.class, info.chenliang.myserver.messages.MyMessages.VersionResponse.Builder.class);
      }

      // Construct using info.chenliang.myserver.messages.MyMessages.VersionResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return info.chenliang.myserver.messages.MyMessages.internal_static_info_chenliang_myserver_messages_VersionResponse_descriptor;
      }

      public info.chenliang.myserver.messages.MyMessages.VersionResponse getDefaultInstanceForType() {
        return info.chenliang.myserver.messages.MyMessages.VersionResponse.getDefaultInstance();
      }

      public info.chenliang.myserver.messages.MyMessages.VersionResponse build() {
        info.chenliang.myserver.messages.MyMessages.VersionResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public info.chenliang.myserver.messages.MyMessages.VersionResponse buildPartial() {
        info.chenliang.myserver.messages.MyMessages.VersionResponse result = new info.chenliang.myserver.messages.MyMessages.VersionResponse(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof info.chenliang.myserver.messages.MyMessages.VersionResponse) {
          return mergeFrom((info.chenliang.myserver.messages.MyMessages.VersionResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(info.chenliang.myserver.messages.MyMessages.VersionResponse other) {
        if (other == info.chenliang.myserver.messages.MyMessages.VersionResponse.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        info.chenliang.myserver.messages.MyMessages.VersionResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (info.chenliang.myserver.messages.MyMessages.VersionResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:info.chenliang.myserver.messages.VersionResponse)
    }

    static {
      defaultInstance = new VersionResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:info.chenliang.myserver.messages.VersionResponse)
    public static final int ID_FIELD_NUMBER = 10001;
    /**
     * <code>extend .info.chenliang.myserver.messages.MessageBase { ... }</code>
     */
    public static final
      com.google.protobuf.GeneratedMessage.GeneratedExtension<
        info.chenliang.myserver.messages.MyMessages.MessageBase,
        info.chenliang.myserver.messages.MyMessages.VersionResponse> id = com.google.protobuf.GeneratedMessage
            .newMessageScopedGeneratedExtension(
          info.chenliang.myserver.messages.MyMessages.VersionResponse.getDefaultInstance(),
          0,
          info.chenliang.myserver.messages.MyMessages.VersionResponse.class,
          info.chenliang.myserver.messages.MyMessages.VersionResponse.getDefaultInstance());
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_info_chenliang_myserver_messages_MessageBase_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_info_chenliang_myserver_messages_MessageBase_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_info_chenliang_myserver_messages_VersionRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_info_chenliang_myserver_messages_VersionRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_info_chenliang_myserver_messages_VersionResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_info_chenliang_myserver_messages_VersionResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020mymessages.proto\022 info.chenliang.myser" +
      "ver.messages\"\233\001\n\013MessageBase\022G\n\004type\030\001 \002" +
      "(\01629.info.chenliang.myserver.messages.Me" +
      "ssageBase.MessageType\"8\n\013MessageType\022\023\n\017" +
      "VERSION_REQUEST\020\001\022\024\n\020VERSION_RESPONSE\020\002*" +
      "\t\010\220N\020\200\200\200\200\002\"~\n\016VersionRequest2l\n\002id\022-.inf" +
      "o.chenliang.myserver.messages.MessageBas" +
      "e\030\220N \002(\01320.info.chenliang.myserver.messa" +
      "ges.VersionRequest\"\200\001\n\017VersionResponse2m" +
      "\n\002id\022-.info.chenliang.myserver.messages.",
      "MessageBase\030\221N \002(\01321.info.chenliang.myse" +
      "rver.messages.VersionResponseB\014B\nMyMessa" +
      "ges"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_info_chenliang_myserver_messages_MessageBase_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_info_chenliang_myserver_messages_MessageBase_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_info_chenliang_myserver_messages_MessageBase_descriptor,
              new java.lang.String[] { "Type", });
          internal_static_info_chenliang_myserver_messages_VersionRequest_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_info_chenliang_myserver_messages_VersionRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_info_chenliang_myserver_messages_VersionRequest_descriptor,
              new java.lang.String[] { });
          internal_static_info_chenliang_myserver_messages_VersionResponse_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_info_chenliang_myserver_messages_VersionResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_info_chenliang_myserver_messages_VersionResponse_descriptor,
              new java.lang.String[] { });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
